### ISSUE TITLE
Add variable results in TypeError

### ISSUE THREAD

**Issue by bolkedebruin** [wepay/airflow-webserver#2]
I tried adding a Variable. Named `test` with `123_test` as a value. This resulted in the following traceback.

```
Traceback (most recent call last):
  File "/home/mbeauchemin/env/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/mbeauchemin/env/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/mbeauchemin/env/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mbeauchemin/env/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mbeauchemin/env/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mbeauchemin/env/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mbeauchemin/env/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mbeauchemin/env/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mbeauchemin/env/lib/python2.7/site-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "/home/mbeauchemin/env/lib/python2.7/site-packages/flask_appbuilder/views.py", line 505, in add
    widget = self._add()
  File "/home/mbeauchemin/env/lib/python2.7/site-packages/flask_appbuilder/baseviews.py", line 914, in _add
    form.populate_obj(item)
  File "/home/mbeauchemin/env/lib/python2.7/site-packages/wtforms/form.py", line 96, in populate_obj
    field.populate_obj(obj, name)
  File "/home/mbeauchemin/env/lib/python2.7/site-packages/wtforms/fields/core.py", line 327, in populate_obj
    setattr(obj, name, self.data)
  File "<string>", line 1, in __set__
    
  File "/home/mbeauchemin/incubator-airflow/airflow/models.py", line 3954, in set_val
    fernet = get_fernet()
  File "/home/mbeauchemin/incubator-airflow/airflow/models.py", line 105, in get_fernet
    return Fernet(str(configuration.get('core', 'FERNET_KEY')))
  File "/home/mbeauchemin/env/lib/python2.7/site-packages/cryptography/fernet.py", line 34, in __init__
    key = base64.urlsafe_b64decode(key)
  File "/usr/lib/python2.7/base64.py", line 119, in urlsafe_b64decode
    """
  File "/home/mbeauchemin/env/lib/python2.7/site-packages/future/types/newstr.py", line 390, in translate
    if ord(c) in table:
TypeError: 'in <string>' requires string as left operand, not int
```

**Comment by jgao54** [comment]
looks like this is relating to FERNET_KEY configuration in airflow.cfg, should work again once a valid fernet key is provided!
