### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by jet2007** [wepay/airflow-webserver#31]
what the port number ?
   

 fabmanager run --app airflow_webserver 

log::::::::
[2017-12-31 03:46:44,919] {base.py:352} INFO - Registering class XComModelView on menu XComs
Traceback (most recent call last):
  File "/bin/fabmanager", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib64/python2.7/site-packages/flask_appbuilder/console.py", line 288, in cli
    cli_app()
  File "/usr/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/flask_appbuilder/console.py", line 120, in run
    _appbuilder.get_app.run(host=host, port=port, debug=debug)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/usr/lib/python2.7/site-packages/Werkzeug-0.13-py2.7.egg/werkzeug/serving.py", line 780, in run_simple
    s.bind((hostname, port))
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use

**Comment by jgao54** [comment]
FAB default port is 8080, you can set the port via `--port` flag

**Comment by jet2007** [comment]
thanks
